// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe9B7JRtlAGpPJqo27-7XZMv1d7xCc8Y0',
    appId: '1:74758815137:web:db3ce1e540deee1ab61fe0',
    messagingSenderId: '74758815137',
    projectId: 'cakelab-3152e',
    authDomain: 'cakelab-3152e.firebaseapp.com',
    storageBucket: 'cakelab-3152e.firebasestorage.app',
    measurementId: 'G-5RJ7HM9Q4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLGUSygQaXyKDhKulpbfsbUgOfwveW-M',
    appId: '1:74758815137:android:0a50011a246e9dfbb61fe0',
    messagingSenderId: '74758815137',
    projectId: 'cakelab-3152e',
    storageBucket: 'cakelab-3152e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwy4lbtwfF4pFA_cnwxPN44JIfctNWZuw',
    appId: '1:74758815137:ios:3337136495b0b9b6b61fe0',
    messagingSenderId: '74758815137',
    projectId: 'cakelab-3152e',
    storageBucket: 'cakelab-3152e.firebasestorage.app',
    iosBundleId: 'com.example.cakeLab',
  );
}
